name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        elixir: [ '1.7', '1.8', '1.9', '1.10', '1.11', '1.12', '1.13' ]
        otp: [ '22', '23', '24' ]
        exclude:
          - elixir: '1.7'
            otp: '23'
          - elixir: '1.7'
            otp: '24'
          - elixir: '1.8'
            otp: '23'
          - elixir: '1.8'
            otp: '24'
          - elixir: '1.9'
            otp: '23'
          - elixir: '1.9'
            otp: '24'
          - elixir: '1.10'
            otp: '24'

    steps:
      - uses: actions/checkout@v2
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-mix-
      - name: Install dependencies
        run: mix deps.get
      - name: Run tests
        run: mix test
